### ISSUE TITLE
`require ? X facets` error with manual installation on macOS

### ISSUE THREAD

**Issue by heoa** [PAIR-code/facets#101]
For the installation, I run

```
$ cd /Users/hhh/anaconda3/share/jupyter/nbextensions
$ git clone https://github.com/PAIR-code/facets
$ jupyter nbextension install facets
$ jupyter nbextension enable facets 
$ cp -r facets/facets-dist .
$ jupyter nbextension install facets-dist
$ jupyter nbextension install facets
```

but I am getting the errors such as 
```
$ jupyter nbextension enable facets
Enabling notebook extension facets...
      - Validating: problems found:
        - require?  X facets
$ jupyter nbextension enable facets-dist/
Enabling notebook extension facets-dist/...
      - Validating: problems found:
        - require?  X facets-dist/
$ jupyter nbextension enable facets-dist
Enabling notebook extension facets-dist...
      - Validating: problems found:
        - require?  X facets-dist
$ jupyter nbextension enable facets-dist/facets-jupyter.html
Enabling notebook extension facets-dist/facets-jupyter.html...
      - Validating: problems found:
        - require?  X facets-dist/facets-jupyter.html
```
I am using Anaconda on macOS 10.12.6.

**Can someone instruct how to install the Google Facets extension on Jupyter Notebooks for macOS? Why am I getting the errors in following the second bullet point of the enumerate point 2 of the instructions [here](https://github.com/PAIR-code/facets)?**

**Comment by jameswex** [comment]
Minimal instructions to get it working should be:

1) git cloning facets outside of your jupyter directory
2) then copying the facets-dist directory from the cloned repo to /Users/hhh/anaconda3/share/jupyter/nbextensions/facets-dist
3) then open run one of the demo notebooks and you should be able to see facets.

If you manually copy the facets-dist folder into the nbextensions folder you won't need to run "jupyter nbextension install facets-dist". Also, running "jupyter nbextension enable facets-dist/" isn't necessary as this extension just holds HTML code and doesn't need to be enabled.

**Comment by heoa** [comment]
@jameswex I got the demos working but I cannot understand how it is enough to have a single HTML file in the folder `/Users/hhh/anaconda3/share/jupyter/nbextensions/facets-dist` in order for the `facets` to work. 

1. Is there any security risks in using the Facets Overview or Facets Pivot in Jupyter? 

2. Does there exist something more than just the Facets Overview (summary, explorative reporting) and the FAcets Pivot?

3. Is there anything like in OpenRefine (old Google Refine) to work with the data? Has Facets anything to do with the facets in OpenRefine? 

4. In other words, does Facets provide any way to manipulate/cluster/rename/refine the data like OpenRefine? Or is just for reporting things?
