### ISSUE TITLE
Question regarding CommonStatitcs 

### ISSUE THREAD

**Issue by chesterchen-gpsw** [PAIR-code/facets#108]
message CommonStatistics {
  //..
  // The minimum number of values in a single example for this feature.
  uint64 min_num_values = 3;
  // The maximum number of values in a single example for this feature.
  uint64 max_num_values = 4;
  // The average number of values in a single example for this feature.
  float avg_num_values = 5;
...
}

In common statistics, for numerical values, base on the code each feature's row
        rc = np.count_nonzero(~np.isnan(row))
        if rc != 0:
          row_counts.append(rc)

Since the logic is calculate one feature(column) at a time, this essentially, turn each non-NAN value into 1. So the row_counts becomes 1 dimension array of 1s. 
Then during the commonstats' calculation, the above definitions are compute as 
      commonstats.min_num_values = int(np.min(value['counts']).astype(int))
      commonstats.max_num_values = int(np.max(value['counts']).astype(int))
      commonstats.avg_num_values = np.mean(value['counts'])

the min of 1s array will always 1, and max of 1s array will be always. 

i am trying to understand, what exactly the " The minimum number of values in a single example for this feature." is try to calculate ? Can you give an example without involve code above ? 
for instance, the feature is user age

Age:
NegInfinite, 5, 10, 15, 20, 25, 55,60,70,88 90,NaN, 100, PositiveInfinite

What's the 
 "The minimum number of values in a single example for this feature." should be ? 

Appreciate your respond

**Comment by jameswex** [comment]
The three values you are asking about will always be 1 when calculating statistics from pandas DataFrames. They only can take on different values when calculating statistics from datasets of tf.Example or tf.SequenceExample protocol buffers. In those cases, for a given data point, for a given feature, there may be any number of feature values.

With tf.Examples, one could image a dataset where each example has a feature "last_5_ids_of_movies_watched", which could contain a list of up to 5 integer IDs. In that case, the stats for the last_5_ids_of_movies_watched might have a min_num_values of 1, max_num_values of 5 and avg_num_values of something in-between 1 and 5.

Does this answer your question?

**Comment by chesterchen-gpsw** [comment]
I looked at the ft.SequenceExample, it looks like the feature value could be array of float numbers

Suppose my feature is the following (using your example) and value is expressed as Array

user_id, last_5_ids_of_movies_watched,
1,             [1,2,3]
2,            [2,3]
4,            [3,4,5,6]

so the min_num_values = 2, max_num_values = 5

Hope this is correct understanding.

**Comment by jameswex** [comment]
Your comment is correct with response to tf.Example. tf.Example protos allow for each feature to have multiple feature values (see the "repeated" keyword in the values in the Feature message). tf.SequenceExample adds yet another layer to this, allowing non-context features to have a list of lists of values (context features in SequencExample are just like features in tf.Examples, in that they can contain a list of values for each feature).

**Comment by chesterchen-gpsw** [comment]
Thanks for comments.
