### ISSUE TITLE
Deep Dive fails to display color and crashes after about 8 seconds on 90k rows

### ISSUE THREAD

**Issue by contractorwolf** [PAIR-code/facets#115]
I have a dataset with 90k rows and 33 columns mostly floats but a few strings for state, device type, and a product name (label column).  I tried it first on the website and it loads the data and displays the overview without issue, but the deep dive didnt seem to display correctly and crashes.  After reading more I saw that if you have a larger dataset you should run it locally in Jupyter Notebook, so I tried that.

Running locally i see the same issue.  The dots werent displaying the color, but if i change the field to display it will momentarily show the colored dots (without displaying the dot labels) and then freeze, and then crash and all the color disappears.  In the Chrome console I just get this:
```
facets-jupyter.html:6708 THREE.WebGLRenderer: image is too big (19328x19264). Resized to 16384x16329 <canvas width=​"19328" height=​"19264">​
```

And in the normal terminal I see this:
```
[I 21:30:03.486 NotebookApp] Malformed HTTP message from ::1: Content-Length too long
[I 21:30:03.494 NotebookApp] Malformed HTTP message from ::1: Content-Length too long
[I 21:32:03.336 NotebookApp] Malformed HTTP message from ::1: Content-Length too long
[I 21:32:03.347 NotebookApp] Malformed HTTP message from ::1: Content-Length too long
[I 21:34:03.688 NotebookApp] Malformed HTTP message from ::1: Content-Length too long
[I 21:34:03.696 NotebookApp] Malformed HTTP message from ::1: Content-Length too long
[I 21:36:01.489 NotebookApp] Starting buffering for ebf4626e-210b-4783-a4ff-8c60d267054b:331A987D52754B23BD6CDD4F62B1342A
[I 21:35:38.795 NotebookApp] Adapting to protocol v5.1 for kernel ebf4626e-210b-4783-a4ff-8c60d267054b
[I 21:37:38.718 NotebookApp] Saving file at /Facets-LT-Alerts.ipynb
[I 21:39:38.712 NotebookApp] Saving file at /Facets-LT-Alerts.ipynb
[I 21:41:43.922 NotebookApp] Saving file at /Facets-LT-Alerts.ipynb
[W 21:41:57.642 NotebookApp] 404 GET /static/components/preact/preact.min.js.map (::1) 9.28ms referer=None
[W 21:41:57.655 NotebookApp] 404 GET /nbextensions/facets-dist/web-animations-next-lite.min.js.map (::1) 3.07ms referer=None
[W 21:41:57.665 NotebookApp] 404 GET /static/components/preact-compat/preact-compat.min.js.map (::1) 2.74ms referer=None
[W 21:41:57.668 NotebookApp] 404 GET /static/components/proptypes/index.js.map (::1) 2.88ms referer=None
[I 21:48:23.813 NotebookApp] Saving file at /Facets-LT-Alerts.ipynb
[I 21:50:56.147 NotebookApp] Saving file at /Facets-LT-Alerts.ipynb
[I 21:51:11.841 NotebookApp] Saving file at /Facets-LT-Alerts.ipynb
[I 21:51:24.285 NotebookApp] Saving file at /Facets-LT-Alerts.ipynb
[I 21:51:35.122 NotebookApp] Starting buffering for ebf4626e-210b-4783-a4ff-8c60d267054b:C6E10B76035F4ABAA3A794752653AC22
[W 21:51:35.337 NotebookApp] 404 GET /static/components/preact/preact.min.js.map (::1) 3.34ms referer=None
[W 21:51:35.341 NotebookApp] 404 GET /static/components/proptypes/index.js.map (::1) 2.38ms referer=None
[W 21:51:35.345 NotebookApp] 404 GET /static/components/preact-compat/preact-compat.min.js.map (::1) 3.29ms referer=None
[I 21:51:47.505 NotebookApp] Adapting to protocol v5.1 for kernel ebf4626e-210b-4783-a4ff-8c60d267054b
[W 21:51:47.610 NotebookApp] 404 GET /nbextensions/facets-dist/web-animations-next-lite.min.js.map (::1) 3.39ms referer=None
```

I am kinda new to Jupyter Notebook and am brand new to Facets, so I dont know what to make of either output.  I am pretty sure that my data is clean, mostly numbers, no blanks or nulls.

What should I try or how can I debug and figure out what the issue is?

**Comment by jimbojw** [comment]
Hi contractorwolf,

The default sprite image size is 64x64 px, which is probably too big for your data set of 90k image. I'd recommend something smaller like 32x32. These are controlled by the `sprite-image-width` and `sprite-image-height` attributes on the `<facets-dive>` element. Or you can set them programmatically by the names `spriteImageWidth` and `spriteImageHeight` respectively.

```html
<facets-dive sprite-image-width="32" sprite-image-height="32" ...></facets-dive>
```

Details about these attributes can be found in the facets_dive/README.md under [Sprite Properties](https://github.com/PAIR-code/facets/tree/master/facets_dive#sprite-properties).

**Comment by contractorwolf** [comment]
@jimbojw thank you so much.  I was trying all sorts of things (noob guesses) and nothing was working, but that seems to have totally solved it.  It is no longer crashing and renders nicely 👍 I owe you a beer.

**Comment by jimbojw** [comment]
Glad it's working! Sorry the error message wasn't more helpful. I'll have to think about how to capture that condition and surface useful guidance.

**Comment by contractorwolf** [comment]
I was attempting to make a PR to change the default size to 32 to facilitate larger datasets, is that not possible? I have never made a public PR before (but plenty with my company).  Is it possible to give me PR permissions?

**Comment by jameswex** [comment]
You can fork the repository, make your changes in your forked repo, then create a PR to merge the change from your fork into the official facets repository.  That is the process we have for contributions.

**Comment by contractorwolf** [comment]
My PR:
https://github.com/PAIR-code/facets/pull/118
