### ISSUE TITLE
Is there a way to view saved HTML files without a webserver?

### ISSUE THREAD

**Issue by tszumowski** [PAIR-code/facets#116]
I am able to generate facets-dive visualizations no problem inside a Jupyter Notebook. Is it possible to save the HTML generated in the notebook to a standalone HTML file, and then view/interact with the visualization in that HTML file, without a webserver up?

My general use case is I'd like to create visualizations and then send the resulting HTML over to colleagues to view/interact without us having to stand up a web server to host that file.

**Comment by jameswex** [comment]
I'm not aware of a way to save off the results of the facets vis from a jupyter notebook as a static html file for others to view. If your colleagues don't have jupyter installed, then your best bet would be to stand up a simple webserver to host facets and the data you wish to show them.

**Comment by tszumowski** [comment]
Ok great. That makes sense. Thank you!
