### ISSUE TITLE
can't load latest facets into jupyter

### ISSUE THREAD

**Issue by Mistobaan** [PAIR-code/facets#117]
Seems that the current facets-dist html file is 7months old and does not contain features like the click+ select.

Re-compiling the view and re-installing the extension I get these error. Looks like something is not 'vulanized' or similar.

![image](https://user-images.githubusercontent.com/112599/38335766-56c56962-3814-11e8-9275-56c6b0d74a7f.png)

Any pointers?

**Comment by jameswex** [comment]
Yes unfortunately the facets build is currently broken because of changes in the build rules we use from TensorBoard (tf_web_library). I am working with them to determine a path forward. Really sorry for the inconvenience and hope to have it sorted out soon.

**Comment by jameswex** [comment]
Build is back to being functional and the facets-dist html has been updated at HEAD. Sorry for the inconvenience!
