### ISSUE TITLE
Dive_demo.ipynb doesn't show the data

### ISSUE THREAD

**Issue by FabricioProjects** [PAIR-code/facets#13]
I'm trying to run the Dive_demo.ipynb example but the HTML interface doesn't show any points. All is set to NONE. I initialized the jupyter as described on readme file:
$ jupyter notebook --NotebookApp.iopub_data_rate_limit=10000000

**Comment by christiansafka** [comment]
I have the same issue, Ubuntu 16.04, Chrome 58.0.3029.110 (64-bit).  The Overview demo was working fine.

**Comment by jameswex** [comment]
@woodrujm @FabricioProjects just curious, does resizing your browser window after the cell runs (and the visualization is empty of points) fix the problem?

Also, if you print out the jsonstr, does it show actual data?

Lastly, can you try in the script tag replacing the first line with "var data = {jsonstr};" (removing the JSON.parse call).

**Comment by FabricioProjects** [comment]
@jameswex Ty for response James but both methods doesn't worked.

**Comment by woodrujm** [comment]
@jameswex did not work for me either

**Comment by Arhno** [comment]
I had the same issue. At some point I added `alert`s to display the data in the dive element before and after the assignement line to make sure everything was set correctly and it sudently worked.
I later realized my PC was running out of RAM (and was swapping a lot) and once I closed some other app the alerts weren't necessary anymore.

Just sharing my experience in case it helps someone.

**Comment by FabricioProjects** [comment]
@Arhno Can you post the part of code that you modified?

**Comment by mstetter** [comment]
Is there already a solution to this issue? I can't display the results either. The jsonstr works fine and is filled, but no points. I'm on mac OS 10.12 with Chrome

**Comment by jameswex** [comment]
do those of you with the issue see any errors in your developers console log (can see this in chrome through cntrl-shift-j keystoke or through the options menu->more tools->developers console)?

**Comment by mstetter** [comment]
The demo shows fine. just not in my own notebook. I checked the developer console and there is only this warning:
`Failed to decode downloaded font: https://fonts.gstatic.com/stats/Roboto/normal/500` 

When I click inside the element that would show the data:
```

facets-jupyter.html:7203 Uncaught TypeError: Cannot read property 'findSprites' of undefined
    at a.clicked (facets-jupyter.html:7203)
    at SVGSVGElement.<anonymous> (facets-jupyter.html:154)
```


what it doesn't display is the data, the other elements are there. The selecters are there too but no selection. same as in the screenshot from @woodrujm

**Comment by Arhno** [comment]
@FabricioProjects I did something like this: 
```
# Display the Dive visualization for this data
from IPython.core.display import display, HTML

HTML_TEMPLATE = """<link rel="import" href="/nbextensions/facets-dist/facets-jupyter.html">
        <facets-dive id="elem" height="600"></facets-dive>
        <script>
          var data = {jsonstr};
          alert(data)
          alert(document.querySelector("#elem").data);
          document.querySelector("#elem").data = data;
          alert(document.querySelector("#elem").data);
        </script>"""
html = HTML_TEMPLATE.format(jsonstr=jsonstr)
display(HTML(html))
```
I really don'tknow if there is causation or just correlation but it worked for me after this modification (and once it started working I could remove the alert and still getting the data to be drawn)

**Comment by FabricioProjects** [comment]
@Arhno lol, it worked :) Ty very much. I'm closing this.
