### ISSUE TITLE
Upload big amounts of data to facets overview

### ISSUE THREAD

**Issue by fatimashihab** [PAIR-code/facets#138]
Hello,

I have to inquiries:

- First, I have about 2 million records or slightly more dataset that I want to visualize on Facets Overview, ofcourse uploading only 100K was enough to slow down my PC for 2 - 3 minutes. Is there more applicable method to visualize 2M records on Facets? If there are any sample code please show me.

- Second,  I created exported an HTML page of Facets Dive directly through the <facets-dive> polymer , however I couldn't use the same method with Facets Overview and had to run it on Jupyter. Is there anything similar to simply replace the <facets-dive> with <facets-overview> or simply export an HTML webpae through simple Python? Also if I'm using Jupyter notebook, how can I export the result in a separate HTML file while using the display(HTML(html)) function.

Here is my code for the facets dive: [https://github.com/fatimashihab/facets/blob/master/facets%20dive/data_visualization.py](url)

and code:
 `HTML_TEMPLATE = u"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>%(title)s</title>
    <script>
        window.addEventListener('DOMContentLoaded', function() {
            var link = document.createElement('link');
            link.rel = "import";
            link.href = "https://raw.githubusercontent.com/PAIR-code/facets/master/facets-dist/facets-jupyter.html";
            link.onload = function() {
                var dive = document.createElement('facets-dive');
                dive.crossOrigin = "anonymous";
                dive.data = %(data)s;
                var presets = %(presets)s;
                for (var key in presets) {
                    if (presets.hasOwnProperty(key))
                        dive[key] = presets[key];
                }
                document.body.appendChild(dive);
            }
            document.head.appendChild(link);
        });
    </script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.7.24/webcomponents-lite.js"></script>
    <style>body, html { height: 100%%; margin: 0; padding: 0; width: 100%%; }</style>
</head>
<body></body>
</html>
""".strip()

#export data
with open(OUTPUT_FILE_PATH, "wb") as f:
    final_template = HTML_TEMPLATE % {
        'title':'Data Visualization',
        'data': dataset.to_json(orient='records'),
        'presets': json.dumps(PRESETS)
    }
    f.write(final_template.encode('utf-8'))`

I appreciate your help, please reply asap. 
Thank you in advance

**Comment by jameswex** [comment]
A team within Google is currently working on open-sourcing an Apache Beam pipeline for generating the statistics proto (which is the required input to facets overview) for giant datasets. As of now, nothing exists in the open-source world to generate the statistics proto for huge datasets. But that should change shortly.

As far as exporting an HTML page for facets overview, like you have shown for facets dive, what problem did you run into? It should work, as that is how our demo page works (https://pair-code.github.io/facets/) - See the code for that page here: https://github.com/PAIR-code/facets/blob/gh-pages/index.html#L231

**Comment by chesterchen-gpsw** [comment]
I just created a project that can use spark to generating protobuf for CSV,
Jason, SQL and tfrecord. The result protobuf can be loaded into jupyter or
JavaScript.
I did the talk at ai nextcon and sf big analytics meetup.

I will clean up the code and put the public repo soon.

https://github.com/chesterxgchen/facet-overview-spark

But this does not solve the issue of if the resulting protobuf size is too
large.

**Comment by jameswex** [comment]
@chesterchen-gpsw that is fantastic! Once the code is cleaned up and you want it publicized, I can add a link to it from the facets overview readme page.

**Comment by chesterxgchen** [comment]
@jameswex  thanks
I just push the code, please take a look
https://github.com/chesterxgchen/facet-overview-spark

Feedback welcome.  I did not use Blaze build, maven is used.

**Comment by chesterxgchen** [comment]
@jameswex 
 GoPro just approved the open source my project. Here is updated github repo
   https://github.com/gopro/facets-overview-spark
 You can make it public now. 

Thanks
Chester

**Comment by jameswex** [comment]
Thanks Chester! I added a reference here: https://github.com/PAIR-code/facets/tree/master/facets_overview#large-datasets
