### ISSUE TITLE
Facets Notebook Example Issue

### ISSUE THREAD

**Issue by hardianlawi** [PAIR-code/facets#161]
For the first plot shown on [here](https://colab.research.google.com/drive/1QrcuNHJnL3TBzcFV-0yw6y3wWmSWv_gM), it doesn't seem like you could change the position X-axis and Y-axis like shown on the [demo page](https://pair-code.github.io/facets/). What is wrong?

**Comment by jameswex** [comment]
I see this behavior too. I will take a look at what is causing Facets Dive to not allow scatter plot creation using the numeric features.
