### ISSUE TITLE
BUILD error facets on OSX 10.14.2

### ISSUE THREAD

**Issue by plopd** [PAIR-code/facets#171]
I have bazel installed using binaries NOT home-brew

<img width="1440" alt="screenshot 2019-01-18 at 11 54 48" src="https://user-images.githubusercontent.com/1534513/51382795-09daa580-1b18-11e9-90b3-d9a1d9da065f.png">

**Comment by jameswex** [comment]
Very recently we also noticed the bazel builds failing unless you use the parameters specified in the error. 

You may need to add these flags to your bazel command while we figure out the root cause:

--incompatible_package_name_is_a_function=false --incompatible_remove_native_http_archive=false
