### ISSUE TITLE
HTML import of "facets-jupyter.html"

### ISSUE THREAD

**Issue by Pindar777** [PAIR-code/facets#175]
While trying in vain to import the file "facets-jupyter.html" from the cloned, local folder into the html (got it to work with "https://raw.githubusercontent.com/PAIR-code/facets/master/facets-dist/facets-jupyter.html") i came across this news:

https://developer.mozilla.org/en-US/docs/Web/Web_Components/HTML_Imports

> HTML Imports are Obsolete since Google Chrome 73
This feature is obsolete. Although it may still work in some browsers, its use is discouraged since it could be removed at any time. Try to avoid using it.

Is google facets to be updated?
And how to link to local files (in order to work offline)?

**Comment by jameswex** [comment]
We plan on upgrading Facets to use Polymer 2 to alleviate this issue. In the meantime, Facets (and all  HTML imports) still works in browsers when using the page loading them also loads the polyfill as mentioned on the page you linked.

If you want to get facets to work offline inside of a Jupyter notebook, you should be able to install the facets-jupyter.html to the correct location following these directions: https://github.com/pair-code/facets#using-the-rebuilt-visualizations-in-a-jupyter-notebook

**Comment by Pindar777** [comment]
@jameswex Thanks for your fast response and help.
