### ISSUE TITLE
link not rendered properly

### ISSUE THREAD

**Issue by dzhang** [PAIR-code/facets#177]
Hi

I am using Facets Dive in Jupyter Notebook, want to display a link on the right panel. I set one of the field value as
img_path= "&lt;a href="http://xxx.jpg">image</a&gt;"

expect to see a link, but saw this displayed

img_path
&lt;a href="http://xxx.jpg">image</a&gt;

Thanks
Dong

**Comment by jimbojw** [comment]
Hi Dong,

Yes, HTML and/or URLs are not rendered in the info card by default. However, you could implement a custom `infoRenderer()` method to do this. This is described in the documentation on [advanced customization properties](https://github.com/PAIR-code/facets/tree/master/facets_dive#advanced-customization-properties).

I'm not sure how you'd do this in a Jupyter notebook, but it requires a little custom JavaScript. Something like this (untested code):

```js
function yourInfoRenderer(dataObject, elem) {
  elem.innerHTML = dataObject.img_path;
}

const dive = document.querySelector('facets-dive')[0];
dive.infoRenderer = yourInfoRenderer;
```

You can see how the default info renderer is implemented in the file [info-renderers.ts](https://github.com/PAIR-code/facets/blob/967e764dd8fbc8327ba9d4e39f3c0d76dce834b9/facets_dive/lib/info-renderers.ts#L26).

**Comment by dzhang** [comment]
got it working, thanks!

**Comment by jimbojw** [comment]
Awesome, thanks for letting us know!
