### ISSUE TITLE
Calling facets overview multiple times in one Jupyter notebook

### ISSUE THREAD

**Issue by mahdiarsadeghi** [PAIR-code/facets#191]
I want to call use facet overview in different blocks of my jupyter notebook. It works fine with the first block, but if I call facets overview the second time in my notebook it will represent the overview of the new data on previous block. Any idea how I can fix it?

**Comment by jameswex** [comment]
I believe you should be OK as long as you give your different facets-overview elements different IDs, and refer to them through those unique IDs. So the second facets-overview cell might look like this below. Notice to two places where we use "elem2" as a unique ID for this facets overview, as opposed to "elem" for the facets-overview element in the facets-overview demo notebook

```HTML_TEMPLATE = """
        <script src="https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/1.3.3/webcomponents-lite.js"></script>
        <link rel="import" href="https://raw.githubusercontent.com/PAIR-code/facets/master/facets-dist/facets-jupyter.html" >
        <facets-overview id="elem2"></facets-overview>
        <script>
          document.querySelector("#elem2").protoInput = "{protostr}";
        </script>"""
html = HTML_TEMPLATE.format(protostr=protostr)
display(HTML(html))```

**Comment by mahdiarsadeghi** [comment]
Interesting, thanks! 

Is there anyway for defining a function for facets overview that can automatically create create different IDs? It might be obvious, I am just curious and like to contribute.
