### ISSUE TITLE
import file not found

### ISSUE THREAD

**Issue by Sisyphus235** [PAIR-code/facets#198]
To whom it may be concerned,

I am confused about how imports work while I cannot find the import file.
The import sentence is 
```
<link rel="import" href="../../../tf-imports/polymer.html">
```
, with the location as facets/facets_overview/components/facets_overview_row_legend/facets-overview-row-legend.html

Thanks a lot!

**Comment by jameswex** [comment]
This dependency is pulled in by the build dependency on " "@org_tensorflow_tensorboard//tensorboard/components/tf_imports:polymer" from the bazel BUILD file in that directory.  You can see the code in the tensorboard repository at https://github.com/tensorflow/tensorboard/tree/master/tensorboard/components/tf_imports that is pulled in.
