### ISSUE TITLE
Facets overview cant show "percentages" button

### ISSUE THREAD

**Issue by youw3** [PAIR-code/facets#203]
i run the Overview_demo.ipynb but it cant show "percentages" button
![image](https://user-images.githubusercontent.com/18373219/71776316-69042500-2fca-11ea-8031-c0c0abd3c365.png)

and homepage it can show 
![image](https://user-images.githubusercontent.com/18373219/71776324-9bae1d80-2fca-11ea-9e87-e88103215f9b.png)

**Comment by jameswex** [comment]
Sorry this isn't documented but the percentages button only shows up when using Facets Overview to compare two datasets, so the magnitude of each histogram would match, regardless of how many datapoints are in each dataset.

**Comment by youw3** [comment]
> Sorry this isn't documented but the percentages button only shows up when using Facets Overview to compare two datasets, so the magnitude of each histogram would match, regardless of how many datapoints are in each dataset.

Thank you for your  reply. i think the percentages button also need be shown in single dataset. lol:) 
Facets has an amazing display GUI, it helps me a lot in data validation!
