### ISSUE TITLE
HTML Imports is deprecated in Chrome

### ISSUE THREAD

**Issue by melgor** [PAIR-code/facets#206]
Hi,
after last update in Mac, facets stop working in Jupyter. Look like that this is main error:
```
HTML Imports is deprecated and has now been removed as of M80. See https://www.chromestatus.com/features/5144752345317376 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.
```

Screen from situation:
![Screenshot 2020-02-06 at 10 23 49](https://user-images.githubusercontent.com/2587438/73923321-f937d180-48ca-11ea-997a-7a60775ddad2.png)

I'm not sure if this is because of my sytem (Chrome Browser) or because of `Facets`

**Comment by jameswex** [comment]
What version of Facets are you using? If you use the latest code at HEAD, or anything past tag 1.0.0, then with the latest example notebooks things should work. 

Check out this example notebook which loads a polyfill for webcomponents-lite.js before trying to load the facets element: https://github.com/PAIR-code/facets/blob/master/facets_dive/Dive_demo.ipynb

**Comment by melgor** [comment]
Thanks for the answer. Adding line 
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/1.3.3/webcomponents-lite.js"></script>
```
make it work again :) 
Thanks!
