### ISSUE TITLE
Visualization is blank after upgrading to Chrome 80

### ISSUE THREAD

**Issue by Bobgy** [PAIR-code/facets#207]
Hi! When I'm identifying root cause for https://github.com/kubeflow/pipelines/issues/3025.

I found it's a problem of facets. Facets use html imports feature which is only supported in Chrome, and therefore has been deprecated. After upgrading to Chrome 80, this feature is finally removed. So visualization following guide in https://github.com/PAIR-code/facets/blob/6a502d8007534ad73fbe49464e14ae02548e5ae5/facets_overview/README.md#visualization no longer works.

Chrome shows an error message in console and the html output is blank
> renderers.js:39 HTML Imports is deprecated and has now been removed as of M80. See https://www.chromestatus.com/features/5144752345317376 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.

**Comment by Bobgy** [comment]
Looks like the only need to fix it is adding the following polyfill
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/1.3.3/webcomponents-lite.js"></script>
```

**Comment by Bobgy** [comment]
In fact, I found that the demo source code is already updated: https://github.com/PAIR-code/facets/blob/master/facets_overview/Overview_demo.ipynb, only the README is still outdated.

**Comment by jameswex** [comment]
Thanks for pointing out the issue with the README. Sorry about that. I've updated all three READMEs in the facets repo with this information.
