### ISSUE TITLE
Facets Dive, sprite size / multiple sprites

### ISSUE THREAD

**Issue by 53RT** [PAIR-code/facets#208]
Hi,
first think you for this awesome tool. It makes data exploration much more convenient. 

Currently I have around 2000 instances for which I have generated a sprite. Ideally I can use an image resolution of choice but it seems that I am limited by the WebGL `Max Texture Size` which is `16384` in my case. So if my sprite image exceeds the `Max Texture Size` in any dimension the sprite is resized and it fails to render the images. 

Is there a solution for using a higher resolution or multiple sprites that would solve this problem?

I am also not quite sure if this problem is WebGL or THREE.js based.

My graphics card is a Nvidia 1080Ti so I should have more memory available

**Comment by jimbojw** [comment]
Sorry, currently, Facets only supports a single sprite sheet, and so it's limited to the size the graphics card can support. We don't currently have plans to support multiple sprite sheets, but if we did, each of them would be limited by the graphics card's maximum. Graphics cards also limit the number of textures that can be simultaneously bound (around 8, IIRC).

One option is to show the low-resolution images in the sprite sheet, and then load a higher-quality image dynamically in response to user interaction. For example, when you click on a sprite, you could pull up the source image in the info pane. This would require some custom coding.

**Comment by 53RT** [comment]
Thanks for the quick and helpful response. 

Showing the full resolution image after selection sounds like a good solution unfortunately I don't know JavaScript or TypeScript that well but maybe I will try to implement something like this.
