### ISSUE TITLE
facets dive problem of zoomed options

### ISSUE THREAD

**Issue by matteopulega** [PAIR-code/facets#209]
Hi everyone,

i'm trying to use Google Facets Dive to rapresent a confusion matrix of data in a jupyter notebook, on Chrome (windows 10).

The problem is that options are incredibly zoomed (like +, - and other rapresentation options). Only reloading the jupyter notebook all the visualization is correctly zoomed. I would like not to reload everytime the page. How can i do?

 I'm using an example and this is my code 

```
HTML_TEMPLATE = """
        <script src="https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/1.3.3/webcomponents-lite.js"></script>
        
        <link rel="import" href="/nbextensions/facets-dist/facets-jupyter.html">
        
        <facets-dive id="fd" height="600"></facets-dive>
        <script>
          var data = {jsonstr};
          var fd = document.querySelector("#fd");
          fd.data = data;
          fd['verticalFacet'] = 'predicted';
          fd['verticalBuckets'] = 8;
          fd['horizontalFacet'] = 'expected';
          fd['horizontalBuckets'] = 8;
          fd['colorBy'] = 'expected';
        </script>
        """

jsonstr = df.to_json(orient='records')

html = HTML_TEMPLATE.format(jsonstr=jsonstr)
display(HTML(html))
```

**Comment by jimbojw** [comment]
Hi @matteopulega, could you provide a screenshot that demonstrates the problem?

**Comment by matteopulega** [comment]
![facets_error](https://user-images.githubusercontent.com/45599916/76304194-3f65c380-62c3-11ea-9504-edce28f14dd5.PNG)

**Comment by matteopulega** [comment]
> Thanks @jimbojw , here it is the screenshot
> 
> ![facets_error](https://user-images.githubusercontent.com/45599916/76304194-3f65c380-62c3-11ea-9504-edce28f14dd5.PNG)

**Comment by jimbojw** [comment]
Should be fixed if you use the now merged [`/facets-dist/facets-jupyter.html`](https://github.com/PAIR-code/facets/blob/master/facets-dist/facets-jupyter.html).

**Comment by ElhamK** [comment]
I just cloned the repo and have the same problem ...

**Comment by ElhamK** [comment]
<img width="1116" alt="Screen Shot 2021-05-09 at 10 00 20 AM" src="https://user-images.githubusercontent.com/12447651/117574895-5feb0280-b0ad-11eb-87f8-3b52fd697cfc.png">

**Comment by Italosayan** [comment]
Same issue
