### ISSUE TITLE
HTML Imports didnot work for the chrome now.

### ISSUE THREAD

**Issue by drzl386** [PAIR-code/facets#211]
Hey, there right now the chrome updated the version 80, the  import function has been removed in M80. The facet image cannot display.

**Comment by jameswex** [comment]
It should work fine if you load the webcomponents polyfill before trying to use facets, as shown in the updated notebooks and documentation: https://github.com/PAIR-code/facets#usage-in-google-colabratoryjupyter-notebooks, https://colab.sandbox.google.com/github/PAIR-code/facets/blob/master/colab_facets.ipynb
