### ISSUE TITLE
How to load image and show Confusion matrix?

### ISSUE THREAD

**Issue by lvchigo** [PAIR-code/facets#22]
How to load image and show Confusion matrix like "Fun Fact" example?
![qq 20170720160023](https://user-images.githubusercontent.com/8186051/28406833-90727072-6d64-11e7-874c-2d4bc4814130.jpg)

**Comment by vfdev-5** [comment]
I found and managed to load my images. As I understood from [here](https://github.com/PAIR-code/facets/tree/master/facets_dive#providing-sprites-for-dive-to-render) I need to create one big image with original images icons packed as it is drawn on the link: 
```
+---------+---------+---------+- - - - -+---------+
|         |         |         |         |         |
|    0    |    1    |    2    |   ...   |    99   |
|         |         |         |         |         |
+---------+---------+---------+- - - - -+---------+
|         |         |         |         |         |
|   100   |   101   |   102   |   ...   |   199   |
|         |         |         |         |         |
+---------+---------+---------+- - - - -+---------+
|         |         |         |         |         |
|   200   |   201   |   202   |   ...   |   299   |
|         |         |         |         |         |
+---------+---------+---------+- - - - -+---------+
|         |         |         |         |         |
     .         .         .        .          .
|    .    |    .    |    .    |    .    |    .    |
     .         .         .          .        .
``` 
Then, update the html : 
```
# Display the Dive visualization for this data
from IPython.core.display import display, HTML

HTML_TEMPLATE = """<link rel="import" href="/nbextensions/facets-dist/facets-jupyter.html">
        <facets-dive id="elem" height="600"
            cross-origin="anonymous"
            sprite-image-width="128"
            sprite-image-height="128">
        </facets-dive>
        <script>
          var data = {jsonstr};
          document.querySelector("#elem").data = data;
          document.querySelector("#elem").atlasUrl = "/notebooks/relative/path/to/atlas_image.jpg";           
        </script>"""
html = HTML_TEMPLATE.format(jsonstr=jsonstr)
display(HTML(html))
```
And make sure that the whole image is not too large to be load by Chrome.

HTH

**Comment by Mistobaan** [comment]
How did you create the overall image from the small images ?

**Comment by vfdev-5** [comment]
@Mistobaan see this [notebook](https://github.com/vfdev-5/CarvanaImageMasking/blob/stale/notebooks/facets_visualization.ipynb) for example

**Comment by jameswex** [comment]
@vfdev-5 great notebook.

I'm closing this issue as it is explained here and at https://github.com/PAIR-code/facets/tree/master/facets_dive#providing-sprites-for-dive-to-render

**Comment by ginaliqili** [comment]
@jameswex , the link you provided does not say how facets dive understands which images (in the sprite atlas) are part of what category? By stitching together images, how would Facets know which indices refer to predicted vs actual, for example?

**Comment by ginaliqili** [comment]
Also, @vfdev-5 , I tried cloning the repo and running the facets_visualizations notebook. It looks like the "train_masks.csv is not found". Am I doing something wrong?

**Comment by vfdev-5** [comment]
@ginaliqili the repository is not intended to stocks [kaggle datasets](https://www.kaggle.com/c/carvana-image-masking-challenge/data). Idea is that when you use this : 

```
from IPython.core.display import display, HTML

HTML_TEMPLATE = """<link rel="import" href="/nbextensions/facets-jupyter.html">
        <facets-dive 
            id="elem" 
            height="750"
            cross-origin="anonymous"
            sprite-image-width="128"
            sprite-image-height="128">
        </facets-dive>
        <script>
          var data = {jsonstr};
          var atlas_url = "{atlas_url}";
          document.querySelector("#elem").data = data;
          document.querySelector("#elem").atlasUrl = atlas_url;
        </script>"""
html = HTML_TEMPLATE.format(jsonstr=json_data, atlas_url=atlas_url)
display(HTML(html))
```
the variable `json_data` is something like : 
```
[{
  "name": "apple",
  "category": "fruit",
  "calories": 95
},{
  "name": "broccoli",
  "category": "vegetable",
  "calories": 50
}]
```
and is ordered. The same is ordered is supposed for images. 

HTH

**Comment by ginaliqili** [comment]
@vfdev-5 Ah ok, that makes sense, thank you!

**Comment by jameswex** [comment]
@ginaliqili The images in the sprite atlas map to the data objects bound to the data property of facets-dive. So the first image in the atlas is the visual display for the element represented by the first entry in the data array (which are dictionaries that could contain keys "expected" and "actual" their appropriate values).

**Comment by brianliu3650** [comment]
Reconstruct the JSON file and include both the "expected" and "predicted" labels for each class. A good reference for anyone who might needs.

https://rare-technologies.com/interactive-confusion-matrix-python/
