### ISSUE TITLE
Support numpy >= 1.23

### ISSUE THREAD

**Issue by robmoore** [PAIR-code/facets#246]
`numpy.asscalar` has been [removed](https://numpy.org/doc/stable/release/1.23.0-notes.html#expired-deprecations) from Numpy in release 1.23.

The function is called in:

- `facets_overview/python/base_generic_feature_statistics_generator.py`
- `facets_overview/facets_overview/base_generic_feature_statistics_generator.py`

The guidance in the docs is to use `numpy.ndarray.item()` instead.

**Comment by Pawank06** [comment]
Hey @robmoore can I work on this issue? Please assign me

**Comment by tuliofalmeida** [comment]
Hey, any update on this?

**Comment by jameswex** [comment]
This should be fixed as of the latest facets code and the pypi package.
