### ISSUE TITLE
Generate proto files to support protobuf 4.x.x and protoc 3.19.0

### ISSUE THREAD

**Issue by AnandInguva** [PAIR-code/facets#254]
Apache beam tests are failing.

In Apache Beam,  it uses   `from facets_overview.generic_feature_statistics_generator import GenericFeatureStatisticsGenerator` at https://github.com/apache/beam/blob/20c8d3a2ba11f3965022e2ba5e12a241a4ec3442/sdks/python/apache_beam/runners/interactive/display/pcoll_visualization.py#L46

and that file imports `facets_overview.feature_statistics_pb2` https://github.com/PAIR-code/facets/blob/d7e51366a4f8cafc571e23529493943cda957bfa/facets_overview/facets_overview/generic_feature_statistics_generator.py#L21,

the `facets_overview.feature_statistics_pb2.py` file is an old generated pb file  and this import fails with the newer version of protobuf(4.22.0) with the warning below.

![image](https://user-images.githubusercontent.com/34158215/219771928-dbb5e3df-bb8d-4757-a088-36d005985b8b.png)

Can we update the `feature_statistics_pb2.py` file and also update protobuf version in the setup.py?

**Comment by jameswex** [comment]
Created a pull request to update the compiled proto file, and will release new pip package once that pull request is submitted

**Comment by AnandInguva** [comment]
> Created a pull request to update the compiled proto file, and will release new pip package once that pull request is submitted

Thanks. Can I know when the next release will happen?

**Comment by jameswex** [comment]
Version 1.0.3 with updated proto is now released. Let me know if you have any issues.

**Comment by AnandInguva** [comment]
I also see one more file at https://github.com/PAIR-code/facets/blob/83c7d9f7fe45854650998457ab3a4f3a0292f0af/facets_overview/facets_overview/feature_statistics_pb2.py#L24

this is the one that causing our tests fail. Can we update this one too?

**Comment by AnandInguva** [comment]
https://github.com/PAIR-code/facets/tree/master/facets_overview/python -> this folder got updated and I think this is not getting used anywhere.

Can we update the pb2 file in the folder https://github.com/PAIR-code/facets/blob/master/facets_overview/facets_overview? Sorry If i was not clear before.

**Comment by jameswex** [comment]
Ah yes, sorry about that! It has now been updated and package version 1.1.0 released.
