### ISSUE TITLE
Neither Overview or Drive works in Firefox.

### ISSUE THREAD

**Issue by qimingj** [PAIR-code/facets#26]
It either hangs the browser, or outputs nothing in my Jupyter notebook. Understand firefox is not supported at this moment, but would love to see them working in browsers other than chrome.

**Comment by jameswex** [comment]
If you add 
"<script src="https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.7.24/webcomponents-lite.js"></script>" as the first statement in the HTML_TEMPLATE, above the <link> element, then it should work in Firefox

**Comment by jameswex** [comment]
I've updated the notebook examples in the repo to include this code. Closing this bug. Please re-open if it doesn't solve your issue. Thanks! Sorry for the long wait.
