### ISSUE TITLE
Getting 404 GET /nbextensions/facets-dist/facets-jupyter.html

### ISSUE THREAD

**Issue by hack-c** [PAIR-code/facets#28]
After installing I'm getting a 404... is this due to missing nbextension config possibly?

```
✔ ~/projects/wisdot 
04:26 $ jupyter notebook --NotebookApp.iopub_data_rate_limit=10000000
[I 04:26:39.830 NotebookApp] [nb_conda_kernels] enabled, 4 kernels found
[I 04:26:40.312 NotebookApp] ✓ nbpresent HTML export ENABLED
[W 04:26:40.313 NotebookApp] ✗ nbpresent PDF export DISABLED: No module named nbbrowserpdf.exporters.pdf
[I 04:26:40.353 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.2.5
[I 04:26:40.358 NotebookApp] [nb_conda] enabled
[I 04:26:40.379 NotebookApp] [nb_anacondacloud] enabled
[I 04:26:40.386 NotebookApp] Serving notebooks from local directory: /Users/charles.hack/projects/wisdot
[I 04:26:40.386 NotebookApp] 0 active kernels 
[I 04:26:40.387 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 04:26:40.387 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
0:42: execution error: "http://localhost:8888/tree" doesn’t understand the “open location” message. (-1708)
[W 04:26:53.917 NotebookApp] 404 GET /api/kernels/8d085097-d70c-4684-b62c-c8918fe91922/channels?session_id=B9C7E2A87D1C4FD185022437200F1AA1 (::1): Kernel does not exist: 8d085097-d70c-4684-b62c-c8918fe91922
[W 04:26:53.946 NotebookApp] 404 GET /api/kernels/8d085097-d70c-4684-b62c-c8918fe91922/channels?session_id=B9C7E2A87D1C4FD185022437200F1AA1 (::1) 38.32ms referer=None
[W 04:27:10.343 NotebookApp] Replacing stale connection: 8d085097-d70c-4684-b62c-c8918fe91922:B9C7E2A87D1C4FD185022437200F1AA1
[I 04:27:38.571 NotebookApp] Saving file at /WisDOT Accidents v170620.ipynb
[I 04:27:38.896 NotebookApp] Saving file at /WisDOT Accidents v170620.ipynb
[W 04:27:43.255 NotebookApp] 404 GET /nbextensions//usr/local/share/jupyter/nbextensions/facets-jupyter.html.js?v=20170721042639 (::1) 4.62ms referer=http://localhost:8888/notebooks/WisDOT%20Accidents%20v170620.ipynb
[W 04:27:43.281 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20170721042639 (::1) 1.65ms referer=http://localhost:8888/notebooks/WisDOT%20Accidents%20v170620.ipynb
[W 04:27:44.536 NotebookApp] 404 GET /nbextensions/facets-dist/facets-jupyter.html (::1) 1.72ms referer=http://localhost:8888/notebooks/WisDOT%20Accidents%20v170620.ipynb
[I 04:27:44.591 NotebookApp] Kernel started: 1f1c3a9e-afee-430c-ac12-6820346bbcf1
```

**Comment by Arhno** [comment]
I think I got the same issue. In my case the html file was located in `/nbextensions/facets-jupyter.html` and not `/nbextensions/facets-dist/facets-jupyter.html` I manually created du the facets-dist folder and copy the file there.

**Comment by bingfengyiren** [comment]
I aslo got this issue.
[W 23:40:47.217 NotebookApp] 404 GET /nbextensions/facets-dist.js?v=20170721234039 (::1) 2.06ms referer=http://localhost:8888/notebooks/facets_dive/Dive_demo.ipynb
[W 23:40:47.242 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20170721234039 (::1) 2.37ms referer=http://localhost:8888/notebooks/facets_dive/Dive_demo.ipynb
[I 23:40:47.792 NotebookApp] Kernel started: 29335be3-89e6-4d5a-bca4-8d6c38acf3bd
[W 23:40:59.818 NotebookApp] 404 GET /api/kernels/eb7ce8eb-a069-4167-933a-a3192dea05a4/channels?session_id=EE45CC4106C949A486CF5966604A718E (::1): Kernel does not exist: eb7ce8eb-a069-4167-933a-a3192dea05a4
[W 23:40:59.820 NotebookApp] 404 GET /api/kernels/eb7ce8eb-a069-4167-933a-a3192dea05a4/channels?session_id=EE45CC4106C949A486CF5966604A718E (::1) 5.99ms referer=None
[W 23:42:10.276 NotebookApp] 404 GET /api/kernels/0cf3b94d-7199-491f-8d49-cf20ba21ca66/channels?session_id=FA21E573BF0146268EB723F828081090 (::1): Kernel does not exist: 0cf3b94d-7199-491f-8d49-cf20ba21ca66

**Comment by jameswex** [comment]
@hack-c did you install jupyter via pip or another mechanism? the nbextension install directions have been updated slightly as they weren't complete for all types of jupyter installs. it now reads:

"If jupyter was installed with pip, you can use jupyter nbextension install facets-dist/ if jupyter was installed system-wide or jupyter nbextension install facets-dist/ --user if installed per-user (run from the facets top-level directory). You do not need to run any follow-up jupyter nbextension enable command for this extension.

Alternatively, you can manually install the nbextension by finding your jupyter installation's share/jupyter/nbextensions folder and copying the facets-dist directory into it."

So, find where your "share/jupyter/nbextensions" folder is for your jupyter installation, then copy the facets-dist directory under there.

**Comment by hack-c** [comment]
I used conda. 

Hmm... I found that the facets-dist wasn't in my anaconda/share/jupyter/nbextensions/. So I did

```
✔ ~/projects/wisdot 
10:16 $ cp -r ../facets/facets-dist/ /Users/charles.hack/anaconda/share/jupyter/nbextensions/
```

But I still get

```
✔ ~/projects/wisdot 
10:27 $ jupyter notebook --NotebookApp.iopub_data_rate_limit=10000000
[W 10:27:17.855 NotebookApp] Unrecognized JSON config file version, assuming version 1
[I 10:27:18.715 NotebookApp] [nb_conda_kernels] enabled, 3 kernels found
[I 10:27:18.857 NotebookApp] ✓ nbpresent HTML export ENABLED
[W 10:27:18.857 NotebookApp] ✗ nbpresent PDF export DISABLED: No module named nbbrowserpdf.exporters.pdf
[I 10:27:18.862 NotebookApp] [nb_conda] enabled
[I 10:27:18.954 NotebookApp] [nb_anacondacloud] enabled
[I 10:27:18.960 NotebookApp] Serving notebooks from local directory: /Users/charles.hack/projects/wisdot
[I 10:27:18.960 NotebookApp] 0 active kernels 
[I 10:27:18.960 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 10:27:18.961 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
0:42: execution error: "http://localhost:8888/tree" doesn’t understand the “open location” message. (-1708)
[W 10:27:25.092 NotebookApp] 404 GET /api/kernels/c1a0e3c4-fee2-448e-8c10-83521af1cf15/channels?session_id=41D47B6A438043AC9C52A1228EB668CA (::1): Kernel does not exist: c1a0e3c4-fee2-448e-8c10-83521af1cf15
[W 10:27:25.125 NotebookApp] 404 GET /api/kernels/c1a0e3c4-fee2-448e-8c10-83521af1cf15/channels?session_id=41D47B6A438043AC9C52A1228EB668CA (::1) 43.17ms referer=None
[W 10:27:31.120 NotebookApp] 404 GET /nbextensions//usr/local/share/jupyter/nbextensions/facets-jupyter.html.js?v=20170722102718 (::1) 3.68ms referer=http://localhost:8888/notebooks/WisDOT%20Accidents%20v170620.ipynb
[W 10:27:32.261 NotebookApp] 404 GET /nbextensions/facets-dist/facets-jupyter.html (::1) 1.72ms referer=http://localhost:8888/notebooks/WisDOT%20Accidents%20v170620.ipynb
[W 10:27:32.411 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20170722102718 (::1) 2.26ms referer=http://localhost:8888/notebooks/WisDOT%20Accidents%20v170620.ipynb
[I 10:27:41.601 NotebookApp] Kernel started: 441f40a7-56a7-450e-9701-d0f2dc39b93d
[W 10:27:41.605 NotebookApp] 404 GET /kernelspecs/Python%20[Root]/logo-64x64.png (::1) 1.67ms referer=http://localhost:8888/notebooks/WisDOT%20Accidents%20v170620.ipynb
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.version
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.version

```

**Comment by hack-c** [comment]
Ok! I got it to work. Here's what I did. 

I created a new conda env and then used pip install jupyter instead of installing with conda. Then using that env/jupyter, reinstalled the facets-dist, and it works great! Little laggy with >10000 records. Still experimenting. This thing is amazing though!! Thank you.

**Comment by jameswex** [comment]
Glad to hear it! Closing this issue down as it seems that if facets-dist is installed in the right location then it works.

**Comment by studynon** [comment]
@hack-c I have done what you sard. But there are still the errors.
