### ISSUE TITLE
can't find html file

### ISSUE THREAD

**Issue by anna-mo** [PAIR-code/facets#32]
七月 24, 2017 4:01:04 下午 io.bazel.rules.closure.http.filter.LoggingFilter handle
信息: 100,565µs /0:0:0:0:0:0:0:1:45886 404 GET /
七月 24, 2017 4:01:04 下午 io.bazel.rules.closure.http.filter.LoggingFilter handle
信息: 4,121µs /0:0:0:0:0:0:0:1:45886 404 GET /favicon.ico
七月 24, 2017 4:02:11 下午 io.bazel.rules.closure.http.filter.LoggingFilter handle
信息: 3,755µs /0:0:0:0:0:0:0:1:45886 404 GET /facets-overview/function-tests/simple/index.html
七月 24, 2017 4:02:38 下午 io.bazel.rules.closure.http.filter.LoggingFilter handle
信息: 3,892µs /0:0:0:0:0:0:0:1:45886 404 GET /facets-overview/function-tests/index.html
after runing bazel i meet this pro, can u solve this, many thanks!

**Comment by jameswex** [comment]
What bazel command did you run and what demo/test/use-case were you trying to see?

**Comment by anna-mo** [comment]
thanks, i had solved this one
