### ISSUE TITLE
Query: What is maximum number of records facets can handle?

### ISSUE THREAD

**Issue by akhilputhiry** [PAIR-code/facets#40]
What will be the maximum no of records facets can handle/ how we can determine the limit to be used.

**Comment by jameswex** [comment]
The limit will depend on the RAM of your machine, and the limit will be different for Facets Overview and Facets Dive.

Do you have a dataset that has failed in one of the visualizations due to size?

**Comment by akhilputhiry** [comment]
@jameswex I wanted to try with some big record sets. Before doing that Just thought of checking with you guys :smile:

**Comment by vatsan** [comment]
Facets dive freezes on a dataset of 1 million+ rows,  250 columns. I have 256 GB RAM.

**Comment by jameswex** [comment]
@vatsan not surprising. We haven't used dive with more than 50k rows.

**Comment by jameswex** [comment]
Closing as the question has been answered. Please re-open if further discussion is needed.
