### ISSUE TITLE
jupyter's demo get 404.

### ISSUE THREAD

**Issue by inoue0426** [PAIR-code/facets#41]
**Environment**
Python 3.6.2 :: Anaconda custom (x86_64)
jupyter --version : 4.3.0

I ran demo code "Dive_demo.ipynb".
Then, it was displayed as "**404 GET /nbextensions/facets-dist/facets-jupyter.html (::1) 7.22ms referer=http://localhost:8888/notebooks/facets_dive/Dive_demo.ipynb**" at terminal.

How can I solve it?

**Comment by jameswex** [comment]
Possibly the same issue as https://github.com/PAIR-code/facets/issues/28? Check out the conversation in that bug and let me know if it helps. You probably just need to ensure that the facets-jupyter.html file is put into the appropriate location for your jupyter installation.

**Comment by inoue0426** [comment]
I got it now.
Thank you!
