### ISSUE TITLE
Bazel error - can't run bazel (mac OS 10.12.6)

### ISSUE THREAD

**Issue by benjaminjohansen** [PAIR-code/facets#45]
Hey,

When I try to run bazel build facets:facets_jupyter I get the following error message:

bazel build facets:facets_jupyter
ERROR: bazel does not currently work properly from paths containing spaces (com.google.devtools.build.lib.runtime.BlazeWorkspace@2d9005a).

Any hints on how to get it working in order for me to see the visualizations?

**Comment by jameswex** [comment]
Does the path you cloned/forked the facets repository to contain spaces? If so, try moving it to a path that doesn't contain spaces. Sounds like a bazel limitation.

**Comment by jameswex** [comment]
Closing this. Please re-open if there is still an issue. Thanks.
