### ISSUE TITLE
Error when creating ProtoFromDataFrames from DataFrame without column names

### ISSUE THREAD

**Issue by dragoon** [PAIR-code/facets#46]
I receive the following error when calling ``ProtoFromDataFrames`` after creating a DataFrame without naming the columns:

```
gfsg = GenericFeatureStatisticsGenerator()
df = pd.DataFrame(my_samples)
proto = gfsg.ProtoFromDataFrames([{'name': 'data', 'table': df}])
```

`0 has type <class 'numpy.int64'>, but expected one of: (<class 'bytes'>, <class 'str'>) for field FeatureNameStatistics.name`

**Comment by jameswex** [comment]
Thanks for finding this.

We can fix this by coercing the column key to a string in base_generic_feature_statistics_generator.py line 177, by doing: name=str(key) instead of name=key.

Do you want to create a pull request with this change? If not, I can make it. Let me know. Thanks.

**Comment by dragoon** [comment]
I'll let you do it, thanks a lot for checking!
