### ISSUE TITLE
How to deploy facets as a webserver and display overview&dive without jupyter notebook. 

### ISSUE THREAD

**Issue by WilliamL1** [PAIR-code/facets#49]
I have to say facets overview and dive is a great job. And i already deployed facets in a docker container  , simultaneously facets-overview can be displayed remotely in chrome with _“xx.xx.xx.xx:6006/facets-overview/functional-tests/simple/index.html”_  . 
But i want to exchange test data with my own csv/images dataset which hardcorded in `simple_test.ts` when `devserver` is running . 
So must i parse dataset  in `typescript` files (such as simple_test.js) ?  
How can i use `python interface` to parse data in server part , and display facets_overview&dive without jupyter notebook , just like a tensorboard start server with `tensorboard --logdir=name1:/path/to/logs/1,name2:/path/to/logs/2` in server 
(e.g. such as parsing data and display remotely in facets overview&dive with tornado) ?

**Comment by jameswex** [comment]
In that case you'll probably want to write your own python webserver that can run the stats generation python code from facets and then can serve up the serialized proto to your own html and JS or TS code that is similar to the function-tests code but instead gets the serialized proto from an ajax request to the server.
