### ISSUE TITLE
Jupyter server get 404

### ISSUE THREAD

**Issue by XhivaW** [PAIR-code/facets#51]
Environment: Python 2.7/ipython 5.4.1 installed in Ubuntu 16.04 without any virtual environment and Jupyter was installed by pip

I've tried both method to install the nbextension (jupyter nbextension install command & directly copy to /usr/local/share/jupyter/nbextension path). Both result in same output as below:

> [I 18:33:47.582 NotebookApp] 0 active kernels
[I 18:33:47.582 NotebookApp] The Jupyter Notebook is running at: http://172.16.2.96:8080/
[I 18:33:47.582 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 18:33:54.933 NotebookApp] 404 GET /nbextensions/facets-jupyter.html.js?v=20170811183347 (172.16.3.131) 11.91ms referer=http://172.16.2.96:8080/notebooks/luoyan/Untitled.ipynb
[W 18:33:54.936 NotebookApp] 404 GET /nbextensions/facets.js?v=20170811183347 (172.16.3.131) 1.89ms referer=http://172.16.2.96:8080/notebooks/luoyan/Untitled.ipynb
[W 18:33:54.938 NotebookApp] 404 GET /nbextensions/facets-dist/main.js?v=20170811183347 (172.16.3.131) 1.88ms referer=http://172.16.2.96:8080/notebooks/luoyan/Untitled.ipynb
[W 18:33:54.940 NotebookApp] 404 GET /nbextensions/facets-dist/.js?v=20170811183347 (172.16.3.131) 1.88ms referer=http://172.16.2.96:8080/notebooks/luoyan/Untitled.ipynb
[W 18:33:54.943 NotebookApp] 404 GET /nbextensions/facet.js?v=20170811183347 (172.16.3.131) 1.90ms referer=http://172.16.2.96:8080/notebooks/luoyan/Untitled.ipynb
[W 18:33:54.945 NotebookApp] 404 GET /nbextensions/facetsmain.js?v=20170811183347 (172.16.3.131) 1.87ms referer=http://172.16.2.96:8080/notebooks/luoyan/Untitled.ipynb
[W 18:33:54.955 NotebookApp] 404 GET /nbextensions/notebook.js?v=20170811183347 (172.16.3.131) 1.76ms referer=http://172.16.2.96:8080/notebooks/luoyan/Untitled.ipynb
[W 18:33:54.958 NotebookApp] 404 GET /nbextensions/facets-dist/facets-jupyter.html.js?v=20170811183347 (172.16.3.131) 1.77ms referer=http://172.16.2.96:8080/notebooks/luoyan/Untitled.ipynb
[W 18:33:54.968 NotebookApp] 404 GET /nbextensions//usr/local/share/jupyter/nbextensions/facets-dist/main.js?v=20170811183347 (172.16.3.131) 1.77ms referer=http://172.16.2.96:8080/notebooks/luoyan/Untitled.ipynb
[W 18:33:54.971 NotebookApp] 404 GET /nbextensions/facets/main.js?v=20170811183347 (172.16.3.131) 1.74ms referer=http://172.16.2.96:8080/notebooks/luoyan/Untitled.ipynb
[W 18:33:54.979 NotebookApp] 404 GET /nbextensions//home/datalab/work/.js?v=20170811183347 (172.16.3.131) 1.80ms referer=http://172.16.2.96:8080/notebooks/luoyan/Untitled.ipynb
[I 18:33:55.127 NotebookApp] Kernel started: 363cbc00-2912-4623-bbdd-251f889af915
[W 18:33:55.193 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20170811183347 (172.16.3.131) 2.40ms referer=http://172.16.2.96:8080/notebooks/luoyan/Untitled.ipynb
[I 18:33:55.635 NotebookApp] Adapting to protocol v5.1 for kernel 363cbc00-2912-4623-bbdd-251f889af915

I also checked other issues but it seems they r in virtual environment. So some solution like re-initialization can not be implemented. 

Will keep working on it.

**Comment by jameswex** [comment]
What does your notebook code look like? It seems to be trying to load "/nbextensions/facets-dist/facets-jupyter.html.js" instead of "/nbextensions/facets-dist/facets-jupyter.html", which is the file that is meant to be installed into the jupyter location.

**Comment by XhivaW** [comment]
@jameswex Thx for reply. 

1. I changed the config file: ~/.jupyter/nbconfig/notebook.json as below:
>{
  "load_extensions": {
    "./jupyter-js-widgets/extension": true,
    "./facets-dist/facets-jupyter.html": true
  }
}

2. And rename the "/nbextensions/facets-dist/facets-jupyter.html" to "/nbextensions/facets-dist/facets-jupyter.html.js" 

Then there is not 404 anymore.

Now when I start a new notebook file, it shows:

>[I 10:30:40.813 NotebookApp] Kernel started: a26adb9a-deca-4876-89e8-b5e17d98e9f5
[I 10:30:41.326 NotebookApp] Adapting to protocol v5.1 for kernel a26adb9a-deca-4876-89e8-b5e17d98e9f5
[I 10:32:40.816 NotebookApp] Saving file at /luoyan/Untitled.ipynb

I guess this means I load the extension successfully?

There is another simple question: if the extension loaded successfully, how do I use it in notebook? Since I don't see any new buttons or similar staffs.

**Comment by jameswex** [comment]
@XhivaW here are some example notebooks for how to use the visualizations:
https://github.com/PAIR-code/facets/blob/master/facets_overview/Overview_demo.ipynb
https://github.com/PAIR-code/facets/blob/master/facets_dive/Dive_demo.ipynb

Please reopen if you have issues following those examples.
