### ISSUE TITLE
empty cells are treated as zeros, all statistics are therefore wrong

### ISSUE THREAD

**Issue by demarant** [PAIR-code/facets#54]
I have uploaded a CSV with empty cells, on the demo site at https://pair-code.github.io/facets/
but all the empty cells are treated as zeros and therefore the calculated statistical values like mean,median, st.dev are wrong. 

See attached Handelsbanken_fonder_DB.xlsx file, e.g. the column "10 ar" contains many (337) empty cells, with no value, but these are wrongly treated as 0 by facets. The median should be 59.4, but facets gives instead 31.5. 

[Handelsbanken_fonder_DB.xlsx](https://github.com/PAIR-code/facets/files/1236472/Handelsbanken_fonder_DB.xlsx)

expected is that empty cells are counted as "missing / nodata" and not used in the statistical calculations.

**Comment by jameswex** [comment]
Thanks for pointing this out, I'll take a look this week

**Comment by jameswex** [comment]
Fixed the issue in the demo website code that caused blank cells in a csv to be treated as zeros. Just pushed fixed so demo site should handle your case correct now.
