### ISSUE TITLE
Features with high cardinality crashes chrome (Overview)

### ISSUE THREAD

**Issue by moustafaaatta** [PAIR-code/facets#55]
I find this library super helpful for data exploration! However, I faced a problem with datasets that have categorical columns with high cardinality since each value is included in the generated proto stats object as a histogram bucket. I couldn't make it work for a dataset with 2.5M records with some columns have +1M unique values, naturally, chrome crashes.

I see that the idea of features whitelist is already implemented, however, there is still no way to pass the list. Anyways, a whitelist would require us checking the features beforehand to get rid of codes/IDs and would prevent us from checking the useful stats of those features like the rate of missing values.

I added the possibility for categorical features to display only the top K values in the histograms.
The idea is that for features with that much cardinality, a histogram wouldn't be very useful. K can be large enough to make sure to capture all values in low cardinality features.
This makes the generated stats object size nearly constant regardless of the sample size taken from the dataset.
Additionally, even in cases where it's still possible to display the visualization ( up to 500K records, maybe more) my browser became a little bit laggy and it takes some time for the visualization to appear. A smaller object speeds it up a lot.

I already have this implemented locally and working with it. If you agree with this approach, let me know and I will submit a PR.

**Comment by jameswex** [comment]
Thanks for the PR! I added some comments and look forward to merging this once they are addressed.
