### ISSUE TITLE
Minimum Jupyter Version

### ISSUE THREAD

**Issue by Mistobaan** [PAIR-code/facets#58]
Is there is a minimum Jupyter version required to run the nbextension? if Yes which one?

**Comment by jameswex** [comment]
I haven't tried it with any older versions at this point. Is there a version that you see a problem with?

**Comment by Mistobaan** [comment]
the nbextensions seemed to not be working pre-jupyter 1.0. What version are you using to develop?

**Comment by jameswex** [comment]
jupyter --version for me returns 4.3.0.

**Comment by jameswex** [comment]
Closing this issue, please reopen if necessary.
