### ISSUE TITLE
can't build with bazel on linux

### ISSUE THREAD

**Issue by reesemarlin** [PAIR-code/facets#66]
I run the command to build and found below errors:
**bazel build facets:facets_jupyter**

ERROR: /home/rum/.cache/bazel/_bazel_rum/145145386566f2ed261e1410aff2d253/external/io_bazel_rules_closure/closure/private/defs.bzl:27:16: The `set` constructor for depsets is deprecated and will be removed. Please use the `depset` constructor instead. You can temporarily enable the deprecated `set` constructor by passing the flag --incompatible_disallow_set_constructor=false
ERROR: error loading package '': Extension file 'closure/private/defs.bzl' has errors
ERROR: error loading package '': Extension file 'closure/private/defs.bzl' has errors
INFO: Elapsed time: 0.125s
FAILED: Build did NOT complete successfully (0 packages loaded)

Then I changed the command to below which is followed with other errors:
**bazel build facets:facets_jupyter --incompatible_disallow_set_constructor=false**

ERROR: /work/facets/facets/BUILD:8:1: every rule of type ts_web_library implicitly depends upon the target '@com_google_javascript_closure_compiler_externs//:com_google_javascript_closure_compiler_externs', but this target could not be found because of: no such package '@com_google_javascript_closure_compiler_externs//': The `set` constructor for depsets is deprecated and will be removed. Please use the `depset` constructor instead. You can temporarily enable the deprecated `set` constructor by passing the flag --incompatible_disallow_set_constructor=false
ERROR: Analysis of target '//facets:facets_jupyter' failed; build aborted
INFO: Elapsed time: 0.414s
FAILED: Build did NOT complete successfully (7 packages loaded)

Please help!

**Comment by kayibal** [comment]
Same issue on OSX

**Comment by jameswex** [comment]
Thanks for reporting -same thing as https://github.com/tensorflow/tensorboard/issues/585 (as we use tensorboard's build system).

I'll fix this just as they did.
