### ISSUE TITLE
Error when running demo

### ISSUE THREAD

**Issue by makroid** [PAIR-code/facets#68]
When I try running:
`bazel run //facets_dive/demo --incomtible_disallow_set_constructor=false`

There's the error:
every rule of type ts_web_library implicitly depends upon the target '@com_google_javascript_closure_compiler_externs//:com_google_javascript_closure_compiler_externs', but this target could not be found because of: no such package '@com_google_javascript_closure_compiler_externs//': The `set` constructor for depsets is deprecated and will be removed. Please use the `depset` constructor instead. You can temporarily enable the deprecated `set` constructor by passing the flag --incompatible_disallow_set_constructor=false

What's missing? How to add the package?

Using ubuntu 14.04
bazel 0.6.1
anaconda3, python 3.6

**Comment by makroid** [comment]
Same issue as https://github.com/PAIR-code/facets/issues/66 ?

**Comment by jameswex** [comment]
Yes, dup of #66 which I just fixed, should be fine now if you sync to HEAD and retry.
