### ISSUE TITLE
Allow multi-select in facets-dive

### ISSUE THREAD

**Issue by jameswex** [PAIR-code/facets#71]
Allow for users to easily select more than one item in facets-dive
  - Multi-select with control-click
  - Perhaps select all items in a given facet-box by clicking the background of that box?

Additionally, users have requested exposing a list of the indices of the selected data items (and not just an array of those data items themselves) as a property or event when selection changes.

Lastly, add a box/highlight around selected items to make it clear which are selected. As discussed, might be easiest to put an svg box around the element on the svg plane behind the canvas.

**Comment by jameswex** [comment]
now can control-click to multi-select and selected items have red outlines, and the list of selected data item indices is exposed. closing this.

**Comment by 53RT** [comment]
Hi James,

sorry for commenting under this issue many years later :-)

I noticed that the `facets-dive-info-card` is not scrollable. In the [dive example](https://pair-code.github.io/facets/) is at least one more field (Workclass) that is not shown in the info-card. 

If multiple items are selected this problem becomes more important. I though you might have a fix for this issue.

**Comment by jimbojw** [comment]
Thanks @53RT, yeah that should probably be scrollable. Probably best to make this a separate issue though.
