### ISSUE TITLE
Specify url

### ISSUE THREAD

**Issue by makroid** [PAIR-code/facets#72]
Just run the test example in facets_dive/components.
When trying to add user defined images, I generated a 800x100 png with 8 symbols in it, put it into the components/facets_dive folder and set 
`atlas-url="test_sprite.png"`
in facets-dive.html
But it's not found.
`INFO: 28,851µs /0:0:0:0:0:0:0:1:51068 404 GET /facets-dive/components/facets-dive/test_sprite.png`
How to specify the url?

**Comment by jimbojw** [comment]
> Just run the test example in facets_dive/components.

Can you paste the command you used to run? This will help me get to the root cause, thanks!

**Comment by makroid** [comment]
I run it as specified in the readme:
`bazel run //facets_dive/components/facets_dive:devserver`
It works but instead of the images in test_sprite.png it shows the default colored circles.
test_sprite.png is in the facets_dive/components/facets_dive folder next to facets-dive.html etc.

**Comment by jimbojw** [comment]
Ok thanks. I believe the problem is that bazel is not picking up your file during the build process. The target `//facets_dive/components/facets_dive:devserver` is defined in the file [facets_dive/components/facets_dive/BUILD](https://github.com/PAIR-code/facets/blob/master/facets_dive/components/facets_dive/BUILD) and depends no the `:test` target.

I think if you add `test_sprite.png` to the `deps` of the test target, bazel should pick it up and include it.

~~~py
ts_web_library(
    name = "test",
    testonly = True,
    srcs = [
        "test.html",
        "test.ts",
        "test_sprite.png",  ### ADD THIS ###
    ],
    path = "/facets-dive/components/facets-dive",
    deps = [
        ":facets_dive",
        "//facets_dive/lib/test:externs",
        "@org_tensorflow_tensorboard//tensorboard/components/tf_imports:web_component_tester",
    ],
)
~~~

**Comment by makroid** [comment]
I included it into the BUILD file, but it still does not show up.
I also changed "atlasUrl" to "test_sprite.png" and spriteImageWidth: 100, spriteImageHeight: 100 in facets-dive.ts, but this also does not help.

**Comment by makroid** [comment]
Ok, if I change settings in facets-dive.html, it works. The docs should note that one has to make this change in the BUILD file:
`To specify the URL to an atlas to use, set the atlasUrl property of the Dive Polymer Element in JavaScript (or the atlas-url attribute in HTML).` 
is not super clear (see also https://github.com/PAIR-code/facets/issues/15)

**Comment by jimbojw** [comment]
Glad you got it to work! Sorry again for the confusion.

**Comment by jimbojw** [comment]
Duplicate of #80
