### ISSUE TITLE
Trouble with running with Bazel (OS 10.12.6)

### ISSUE THREAD

**Issue by debclarifai** [PAIR-code/facets#77]
Getting the following error from Bazel attempts:

ERROR: /private/var/tmp/_bazel_debraji/4a5c48c7124814fee87ce4b6b5ca6383/external/io_bazel_rules_closure/closure/private/defs.bzl:27:16: The `set` constructor for depsets is deprecated and will be removed. Please use the `depset` constructor instead. You can temporarily enable the deprecated `set` constructor by passing the flag --incompatible_disallow_set_constructor=false.
ERROR: error loading package '': Extension file 'closure/private/defs.bzl' has errors.
INFO: Elapsed time: 0.055s

Which version of Bazel would I be running to avoid this error?

**Comment by gerard0315** [comment]
if you installes jdk9 you might encounter similar error. try jdk8

**Comment by jameswex** [comment]
See #66, this should be fixed if you sync to head and rebuild, as the bazel rules closure dep in the WORKSPACE file has been updated to commit 4af89ef1db659eb41f110df189b67d4cf14073e1 from 2017-8-28. Please open if this doesn't work for you, thanks.
