### ISSUE TITLE
Make python code pip-installable

### ISSUE THREAD

**Issue by jameswex** [PAIR-code/facets#8]
Make the facets-overview python code pip-installable and upload it to pypi. Update the documentation and examples to install using pip.

**Comment by dsmilkov** [comment]
I did this for https://github.com/PAIR-code/saliency. You can copy `setup.cfg` and make small edits to `setup.py` from that repo. Then follow instructions in https://packaging.python.org/en/latest/distributing.html

**Comment by jimdowling** [comment]
It would also be great to make the python code also available in the default Conda repository. That way we can use the Jupyter extension with our version of Jupyter that doesn't store notebooks on the local filesystem.

**Comment by brandondutra** [comment]
+1 to a pip install version.  Issue #15 recommends a bad user experience for using this in a notebook: no one wants to write html to plot a dataframe.

**Comment by dartdog** [comment]
+ 1 for a conda package.. It is the main way many Data scientists are managing their environments.. I'm staring at the instructions now and trying to figure out where to put the git clone and how to proceed and for instance whether to installation only to my base coda en (which Fuse t run the notebook itself or to install in my py36 environment which actually runs most notebooks (while the server runs the base jupyter environment) Any guidance?

**Comment by kwlzn** [comment]
this would be great.

**Comment by jimdowling** [comment]
I broke this out into a new project for our use. It's a branch here:
https://github.com/hopshadoop/facets/tree/pip_install
The pip package is here (package name is 'hopsfacets'):
https://pypi.python.org/pypi/hopsfacets/0.0.2

pip install hopsfacets

Then code looks like this:
# Calculate the feature statistics proto from the datasets and stringify it for use in facets overview
from hopsfacets.generic_feature_statistics_generator import GenericFeatureStatisticsGenerator
import base64

gfsg = GenericFeatureStatisticsGenerator()
proto = gfsg.ProtoFromDataFrames([{'name': 'train', 'table': train_data},
                                  {'name': 'test', 'table': test_data}])
protostr = base64.b64encode(proto.SerializeToString()).decode("utf-8")

from IPython.core.display import display, HTML

HTML_TEMPLATE = """<link rel="import" href="/nbextensions/facets-dist/facets-jupyter.html" >
        <facets-overview id="elem"></facets-overview>
        <script>
          document.querySelector("#elem").protoInput = "{protostr}";
        </script>"""
html = HTML_TEMPLATE.format(protostr=protostr)
display(HTML(html))

**Comment by varunsimhab** [comment]
Noob here..
When i try to install using what @jimdowling  has provided i get :
---->No matching distribution found for tensorflow (from hopsfacets)

**Comment by NitinAgg** [comment]
Following up on this. Should be an easy fix.

**Comment by kvalev** [comment]
Any plans to create an official PyPI package? It seems that the latest version provided by @jimdowling is broken and the one before that is over a year old.

**Comment by jimdowling** [comment]
@kvalev  - our version works with python 2.7. Need to fix it to work with python 3.

**Comment by jameswex** [comment]
Sorry that this issue hasn't been resolved. I've been putting most of my effort into the What-If Tool which is pip-installable and includes the Facets visualizations (but not the python code to generate statistics for Facets Overview).

I would like to create an official pip package for Facets for py2 and py3, but haven't had the bandwidth to take it on yet.

**Comment by jameswex** [comment]
Created facets-overview pip package, uploaded demo notebooks and readme for its usage. Works in py2 and py3.  Sorry for the huge delay in this.
