### ISSUE TITLE
Atlas image too small to accommodate atlas capacity.

### ISSUE THREAD

**Issue by debclarifai** [PAIR-code/facets#81]
Keep getting this error. 

I'm not sure why - where is capacity variable set?  Does this have to do with the number of entries in the son string and matching that up with the number of spites on the atlas? Please help!

**Comment by jimbojw** [comment]
Hi debclarifai,

That error indicates that your atlas image is too small to contain the desired number of sprites, based on the sprite width and height and the number of data points.

For example, say your sprites are 100 pixels by 100 pixels, and you have 9 data points.

```html
<facets-dive sprite-image-width="100" sprite-image-height="100"></facets-dive>
```

```js
const data = 'ABCDEFGHI'.split('').map(chr => ({chr})); // [{chr: 'A'}, {chr: 'B'}, ...]
const dive = document.querySelector('facets-dive');
dive.data = data;
dive.atlasUrl = 'your-sprite-atlas.png';
```

In this case, the underlying `SpriteAtlas` class expects to receive an image with at minimum, 90,000 total pixels. That is, 100 x 100 x 9. You might lay these out in like a 300x300 tic-tac-toe board:

```text
+---+---+---+
| A | B | C |
+---+---+---+
| D | E | F |
+---+---+---+
| G | H | I |
+---+---+---+
```

Or you could lay them out in one long 900x100 line:

```text
+---+---+---+---+---+---+---+---+---+
| A | B | C | D | E | F | G | H | I |
+---+---+---+---+---+---+---+---+---+
```

Facets Dive is agnostic as to how you stitch together the sprites as long as they start at the top-left and proceed across and down in rows. That is, it will infer the geometry based on the width and height of the atlas image.

However, if the atlas image is too small to accommodate all the data points, at the size indicated by the `sprite-image-width` and `sprite-image-height`, then there is a problem. Either the sprites are actually smaller than the width and height specified, or the atlas image doesn't have enough sprites.

The default sprite image size is 64x64, defined in [`facets-dive-vis.ts`](https://github.com/PAIR-code/facets/blob/master/facets_dive/components/facets_dive_vis/facets-dive-vis.ts#L40). If your sprites are smaller than this, you should set the `sprite-image-width` and `sprite-image-height` properties to match.

More docs on these settings can be found in the [facets-dive/README.md](https://github.com/PAIR-code/facets/tree/master/facets_dive#sprite-properties).

**Comment by debclarifai** [comment]
Thanks, this solved my issue!
