### ISSUE TITLE
Unable to view sprite atlas in Dive

### ISSUE THREAD

**Issue by dhaners** [PAIR-code/facets#82]
I have installed Facets to be used in a jupyter notebook and followed the instructions on the github page. I tried to load the provided notebook, Dive_demo.ipynb, but I am unable to view any data points (although clicking on different areas inside the image does display information on the right hand side).
![image](https://user-images.githubusercontent.com/26175216/32391435-4a0ac4b2-c08f-11e7-9938-ab981d502759.png)

This same visualization displays properly on the facets website https://pair-code.github.io/facets/. 
![image](https://user-images.githubusercontent.com/26175216/32391499-90e09baa-c08f-11e7-9d41-651a42c81eaa.png)

Is there any additional setup I must complete to view the default sprite atlas?

**Comment by jameswex** [comment]
Interesting problem. Do you see any errors in the developers console for the browser when you run the cell that renders the visualization (control-shift-i and then click on the console tab, if using chrome)?

Seems like it might be web-gl related as web-gl is used to render the sprites in the visualization.

**Comment by dhaners** [comment]
Hmm yes I do see web-gl related messages in the developers console:

![image](https://user-images.githubusercontent.com/26175216/32751115-e713bda0-c881-11e7-925b-9b5f09c48d6f.png)

How might I be able to fix that?

**Comment by jameswex** [comment]
Do you not see these same errors if in the same browser you go to the facets website and view Facets Dive?

**Comment by dhaners** [comment]
Yes now that I am looking the website shows the same thing. When I was looking at the website earlier I was using my local browser but I actually want to be able to view this in my VM, which is where I am seeing these errors.

**Comment by jimbojw** [comment]
> ... I actually want to be able to view this in my VM, which is where I am seeing these errors.

That makes sense. To make WebGL work with a VM, there are different steps for different VM providers, graphics drivers and guest OSs. It sounds like you may need to troubleshoot WebGL + your VM setup first before using Dive.

**Comment by jameswex** [comment]
Closing this issue as it is a problem with using webGL with a VM, outside the scope of Facets
