### ISSUE TITLE
Facets Dive show blank plot with my dataset

### ISSUE THREAD

**Issue by secsilm** [PAIR-code/facets#87]
I love the facets idea and want to use it in my work. When I use the `test.csv` from [kaggle Sberbank Russian Housing Market dataset](https://www.kaggle.com/c/sberbank-russian-housing-market/data), Dive show a blank plot.

![dive](https://i.imgur.com/CJvZjfD.png)

Code

```python
test_data = pd.read_csv('test.csv')
jsonstr = test_data.to_json(orient='records')
HTML_TEMPLATE = """<link rel="import" href="/nbextensions/facets-dist/facets-jupyter.html">
        <facets-dive id="elem" height="600"></facets-dive>
        <script>
          var data = {jsonstr};
          document.querySelector("#elem").data = data;
        </script>"""
html = HTML_TEMPLATE.format(jsonstr=jsonstr)
display(HTML(html))
```

FYI, the Overview works fine.

Thank you.

**Comment by jameswex** [comment]
I was able to look at this csv in dive in jupyter on my machine using the following command to start jupyter:
 jupyter notebook --NotebookApp.iopub_data_rate_limit=1000000000

Did you see any IO pub rate warnings in your console? This is a pretty big dataset for dive (in terms of number of examples and features per example), so perhaps that was your issue.

Also can  you check to see that the pandas dataframe was correctly loaded, containing the expected rows and columns?

My data loading cell:
import pandas as pd
df = pd.read_csv(
    "/usr/local/google/home/jwexler/Downloads/test.csv",
    sep=r'\s*,\s*',
    engine='python',
    na_values="?")
jsonstr = df.to_json(orient='records')

My visualization cell:
from IPython.core.display import display, HTML

HTML_TEMPLATE = """<link rel="import" href="/nbextensions/facets-dist/facets-jupyter.html">
        <facets-dive id="elem" height="600"></facets-dive>
        <script>
          var data = {jsonstr};
          document.querySelector("#elem").data = data;
        </script>"""
html = HTML_TEMPLATE.format(jsonstr=jsonstr)
display(HTML(html))

**Comment by secsilm** [comment]
Thank you for your reply. It just works  today. 😄
