### ISSUE TITLE
Demo files won't run

### ISSUE THREAD

**Issue by JayDeeeee** [PAIR-code/facets#95]
Facets seems interesting to me. So I tried to open the two Demo-Notebooks. But i got errors on both of the demos. 

It would be great if someone could help me :)

Here are screenshots of the errors i got. 

![overview_demo1](https://user-images.githubusercontent.com/26609632/33853516-892a8f72-debe-11e7-99c0-7854d3561aa4.png)
![dive_demo1](https://user-images.githubusercontent.com/26609632/33853517-894b6c88-debe-11e7-95f2-7da4b43e9ce8.png)

Thank you in advance!
Janik

**Comment by jameswex** [comment]
For Facets Overview, you will need to have google's protobuf python library installed (i.e. pip install protobuf, or conda install protobuf, or install from source through github). You can do this through installing protobuf directly, or installing tensorflow which depends on protobuf). It seems I left this out of the README, my apologies.

For Facets Dive, see this note from the main Facets README.md:

Note: When visualizing a large amount of data, as is done in the Dive demo Jupyter notebook, you will need to start the notebook server with an increased IOPub data rate. This can be done with the command jupyter notebook --NotebookApp.iopub_data_rate_limit=10000000.

Closing this issue. Please reopen if you still have issues.
